name: Build and Push Docker Container
on: push
jobs:
  build-container:
    name: Build Docker Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Pull Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile 
          pull: true
          tags: nextwebapp:latest
        
      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: docker.io/khushis/nextwebapp:latest
          
          
