name: Integrate Node Application
on: push
jobs:
    build-node:
        name: Build Node
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Install NPM
              run: npm i
            - name: Build assests
              run: npm run build 
            - name: Upload static-site artifacts
              uses: actions/upload-artifact@v3
              with:
                    name: static-site
                    path: .next/
